# PRE-REQUISITES
-- Table Batch( bid,name,start_dt) should exist in myworld database. 
-- bid int AI PK 
-- name varchar(50) 
-- start_dt timestamp

#-----------------------------------------------------------------------
#  DEMONSTRATING CREATE(INSERT) OPERATION
#-----------------------------------------------------------------------

# Creating a new table 
use myworld;
DROP TABLE IF EXISTS myworld.scaler_student;
CREATE TABLE myworld.scaler_student (
    id INT AUTO_INCREMENT,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    dateOfBirth DATE NOT NULL,
    enrollmentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    psp DECIMAL(5, 2) CHECK (psp BETWEEN 0.00 AND 100.00),
    batchId INT,
    isActive BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id),
    FOREIGN KEY(batchId) REFERENCES batch(bid) ON UPDATE SET NULL ON DELETE SET NULL
);
DESC myworld.scaler_student;
COMMIT; 

# Creating/inserting a new row/record into existing table. 
# NOTE: Good practice to mention columns while insert records as some columns might have default values, autogenerated values.

-- Scenario 1: Putting date in wrong format(default is yyyy-mm-dd)
INSERT INTO scaler_student (firstName, LastName, email, dateOfBirth, psp, batchId) 
VALUES ('Razat','Aggarwal','razat.javaprogrammer@gmail.com','09-11-1996',97.4,2);
-- Error Code: 1292. Incorrect date value: '09-11-1996' for column 'dateOfBirth' at row 1

INSERT INTO scaler_student (firstName, LastName, email, dateOfBirth, psp, batchId) 
VALUES ('Razat','Aggarwal','razat.javaprogrammer@gmail.com','1996-11-09',97.40,2);

#-----------------------------------------------------------------------
#  DEMONSTRATING READ OPERATION
#-----------------------------------------------------------------------
use sakila;



#-----------------------------------------------------------------------
#  DEMONSTRATING UPDATE OPERATION
#-----------------------------------------------------------------------


#-----------------------------------------------------------------------
#  DEMONSTRATING DELETE OPERATION
#-----------------------------------------------------------------------